export const ADVISOR_CHAT_MODEL = "gpt-4o-mini-2024-07-18";

export const ADVISOR_SEMANTIC_RESULT_LIMIT = 4;
export const ADVISOR_RECENT_RESULT_LIMIT = 2;
export const ADVISOR_CONTEXT_SOURCE_LIMIT = 5;
export const ADVISOR_MINIMUM_SIMILARITY = 0.5;
export const ADVISOR_HISTORY_MESSAGE_LIMIT = 30;
export const ADVISOR_MESSAGE_CHARACTER_LIMIT = 4000;
export const ADVISOR_MAX_OUTPUT_TOKENS = 600;
